on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Substitua '3.x' pela versão específica do Python que você deseja usar, por exemplo, '3.9'


      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_LOGIN_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build
        id: build-docker-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t $REGISTRY/desafio-devops:$TAG .
          docker tag $REGISTRY/desafio-devops:$TAG $REGISTRY/desafio-devops:latest
          docker push --all-tags $REGISTRY/desafio-devops
          IMAGE=$(echo $REGISTRY/desafio-devops:$TAG)
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy to app runner
        id: deploy-app-runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: ${{ vars.SERVICE_NAME }}
          image: ${{ steps.build-docker-image.outputs.image }}
          access-role-arn: ${{ secrets.AWS_APP_RUNNER_ROLE }}
          region: ${{ secrets.AWS_REGION }}
          cpu: 1
          memory: 2
          port: 8000
          wait-for-service-stability-seconds: 180

      - name: App Runner check
        run: echo "App Runner running... ${{ steps.deploy-app-runner.outputs.service-url }}"